import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppinsFont = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Foodi | Create Next App",
  description: "Foodi | Generated by create next app",

  openGraph: {
    title: "Foodi | Create Next App",
    description: "Foodi | Generated by create next app",
    url: "/og-image.png",
    siteName: "Foodi",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Foodi | Create Next App",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Foodi | Create Next App",
    description: "Foodi | Generated by create next app",
    images: ["/og-image.png"],
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${interFont.className} ${poppinsFont.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col bg-col-6">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
